name: 'Test Action'
description: 'Greet someone and record the time'
inputs:
  token:  # id of input
    description: 'GH Token'
    required: true
    default: ${{ github.token }}
  pr:
    description: 'which pr it is'
    required: true
    default: ${{ github.event.pull_request.number }}
runs:
  using: 'node16'
  main: 'dist/index.js'